import JSZip from 'jszip';
import { getAllUserProjectsGenerator } from './api_user.js';
import { getProjectHtml } from './api_html.js';
import { getAssets, processAssets } from './api_assets.js';
import { getAllProjectRevisions, getProjectById, getProjectBySlug } from './api_project.js';
import { addToCatalog, isArchived, getCatalogAsArray, clearCatalog } from './catalog.js';

// --- State ---
const SETTINGS_KEY = 'websim_archiver_settings';
let isRunning = false;
let stopRequested = false;
let foundProjects = [];
let processedCount = 0;
let zip = null; // Used for Batch mode
let currentZipSize = 0;

// --- DOM Elements ---
const usernameInput = document.getElementById('username');
const startBtn = document.getElementById('start-btn');
const stopBtn = document.getElementById('stop-btn');
const projectListEl = document.getElementById('project-list');
const statTotal = document.getElementById('stat-total');
const statProcessed = document.getElementById('stat-processed');
const statSize = document.getElementById('stat-size');

// Settings Elements
const dateStartInput = document.getElementById('date-start');
const dateEndInput = document.getElementById('date-end');
const downloadModeInput = document.getElementById('download-mode');
const delayInput = document.getElementById('delay-ms');
const skipForksInput = document.getElementById('skip-forks');
const includeHistoryInput = document.getElementById('include-history');
const skipArchivedInput = document.getElementById('skip-archived');

// History UI
const historyBtn = document.getElementById('history-btn');
const historyPanel = document.getElementById('history-panel');
const closeHistoryBtn = document.getElementById('close-history-btn');
const clearHistoryBtn = document.getElementById('clear-history-btn');
const historyListEl = document.getElementById('history-list');
const historyStatsEl = document.getElementById('history-stats');

// --- History Logic ---
const renderHistory = () => {
    const items = getCatalogAsArray();
    historyStatsEl.textContent = `${items.length} projects archived`;
    historyListEl.innerHTML = items.length === 0 
        ? '<div style="padding:2rem; text-align:center; color:var(--text-dim)">No history found.</div>' 
        : '';
    
    items.forEach(item => {
        const div = document.createElement('div');
        div.className = 'history-item';
        const dateStr = new Date(item.timestamp).toLocaleString();
        div.innerHTML = `
            <div class="history-item-info">
                <strong>${item.title}</strong>
                <span class="history-item-date">${item.username} / ${item.slug} • ${dateStr}</span>
            </div>
            <div class="status-icon done" style="width:20px; height:20px; font-size:0.7rem;">✓</div>
        `;
        historyListEl.appendChild(div);
    });
};

historyBtn.addEventListener('click', () => {
    renderHistory();
    historyPanel.classList.remove('hidden');
});

closeHistoryBtn.addEventListener('click', () => {
    historyPanel.classList.add('hidden');
});

clearHistoryBtn.addEventListener('click', () => {
    if(confirm('Clear all local download history? Processing will restart from scratch.')) {
        clearCatalog();
        renderHistory();
    }
});

// --- Helpers ---
const generateGitRestoreScript = () => {
    return `#!/bin/bash
set -e

# WebSim Project Restoration Script
# Generated by WebSim Archiver

if [ -d ".git" ]; then
    echo "Error: .git directory already exists. Please run this in an empty folder or clean it first."
    exit 1
fi

echo "Initializing Git Repository..."
git init -b main

# Check for commit log
if [ ! -f "commit_log.txt" ]; then
    echo "Error: commit_log.txt not found."
    exit 1
fi

TOTAL_VERSIONS=$(wc -l < commit_log.txt)
CURRENT=0

echo "Found $TOTAL_VERSIONS versions to restore."

while IFS="|" read -r ver date author msg; do
    CURRENT=$((CURRENT+1))
    echo "[git-restore] Processing Version \${ver} (\${CURRENT}/\${TOTAL_VERSIONS})..."
    
    # 1. Clean working directory safely
    # Removes everything except .git, revisions, scripts, and logs
    find . -maxdepth 1 -not -name '.git' -not -name 'revisions' -not -name 'restore_git.sh' -not -name 'commit_log.txt' -not -name '.' -not -name '..' -exec rm -rf {} +
    
    # 2. Copy files from revision snapshot
    if [ -d "revisions/\${ver}" ]; then
        # Copy hidden files too if they exist, suppress error if empty
        cp -a "revisions/\${ver}/." . 2>/dev/null || true
    else
        echo "Warning: Revision \${ver} data not found, skipping files..."
    fi
    
    # 3. Git Commit
    git add .
    
    # Check for changes
    if git diff --cached --quiet; then
        echo "  - No changes detected (empty commit)."
        GIT_AUTHOR_DATE="\${date}" GIT_COMMITTER_DATE="\${date}" git commit --allow-empty -m "Version \${ver}: \${msg} (No Changes)" --author="\${author} <\${author}@websim.ai>" --quiet
    else
        GIT_AUTHOR_DATE="\${date}" GIT_COMMITTER_DATE="\${date}" git commit -m "Version \${ver}: \${msg}" --author="\${author} <\${author}@websim.ai>" --quiet
    fi
    
done < commit_log.txt

echo "----------------------------------------"
echo "Restoration Complete!"
echo "You can now delete the 'revisions' folder, 'commit_log.txt', and 'restore_git.sh'."
`;
};

const formatBytes = (bytes, decimals = 2) => {
    if (!+bytes) return '0 Bytes';
    const k = 1024;
    const dm = decimals < 0 ? 0 : decimals;
    const sizes = ['Bytes', 'KB', 'MB', 'GB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return `${parseFloat((bytes / Math.pow(k, i)).toFixed(dm))} ${sizes[i]}`;
};

const createProjectElement = (project) => {
    // Robust fallback for project properties
    const safeTitle = project.title || project.name || project.slug || project.id || 'Untitled';
    const safeSlug = project.slug || project.id;
    const safeId = project.id;

    const el = document.createElement('div');
    el.className = 'project-item';
    el.id = `proj-${safeId}`;
    el.innerHTML = `
        <div class="status-icon pending" id="icon-${safeId}">●</div>
        <div class="project-info">
            <span class="project-name">${safeTitle}</span>
            <div class="project-meta">
                <span>/${safeSlug}</span>
                <span id="log-${safeId}" class="log-msg">Waiting...</span>
            </div>
        </div>
    `;
    return el;
};

const updateStatus = (projectId, status, msg) => {
    const icon = document.getElementById(`icon-${projectId}`);
    const log = document.getElementById(`log-${projectId}`);
    if (!icon || !log) return;

    // Reset classes
    icon.className = 'status-icon';
    if (status === 'loading') icon.classList.add('loading');
    else if (status === 'done') icon.classList.add('done');
    else if (status === 'error') icon.classList.add('error');
    else icon.classList.add('pending');

    icon.textContent = status === 'done' ? '✓' : (status === 'error' ? '!' : '●');
    log.textContent = msg;
};

// --- Core Logic ---

async function processProject(project, username, options) {
    if (stopRequested) return;
    
    const { mode, rootZipFolder, includeHistory } = options;
    const uiId = project.id; 

    console.log(`[Main] Processing project: ${project.id} (slug: ${project.slug})`);
    
    try {
        // --- Setup Zip Target ---
        const targetZip = mode === 'individual' ? new JSZip() : rootZipFolder;
        const projectFolderName = project.slug || project.id || `project_${project.id}`;
        const outputFolder = mode === 'individual' ? targetZip : targetZip.folder(projectFolderName);

        // --- PATH 1: Full History ---
        if (includeHistory) {
            updateStatus(uiId, 'loading', 'Fetching all revisions...');
            
            // 1. Get All Revisions
            let revisions = await getAllProjectRevisions(project.id);
            if (!revisions || revisions.length === 0) {
                // Fallback if revisions list empty (shouldn't happen for valid projects)
                console.warn(`[History] No revisions found via API, falling back to basic metadata.`);
                
                const fallbackVer = project.current_version || 
                                    project.latest_version?.version || 
                                    project.latest_revision?.version || 
                                    1;

                revisions = [{
                    id: project.current_revision?.id,
                    version: fallbackVer,
                    created_at: project.created_at,
                    created_by: project.created_by
                }];
            }

            // 2. Sort Revisions (Oldest -> Newest) for Git History
            revisions.sort((a, b) => (a.version || 0) - (b.version || 0));
            
            if (revisions.length === 0) {
                 throw new Error("No revisions found to archive.");
            }

            // Filter out duplicates based on version just in case
            const uniqueRevisions = [];
            const seenVersions = new Set();
            for (const r of revisions) {
                if (!seenVersions.has(r.version)) {
                    seenVersions.add(r.version);
                    uniqueRevisions.push(r);
                }
            }
            revisions = uniqueRevisions;

            console.log(`[History] 🗓️ Found ${revisions.length} revisions. Range: ${revisions[0]?.version} -> ${revisions[revisions.length-1]?.version}`);
            updateStatus(uiId, 'loading', `Found ${revisions.length} revs. Starting archive...`);

            const revisionsFolder = outputFolder.folder('revisions');
            let commitLog = "";

            // 3. Loop Revisions
            for (let i = 0; i < revisions.length; i++) {
                if (stopRequested) throw new Error("Stopped by user");
                
                const rev = revisions[i];
                let vNum = rev.version;

                // Robust version recovery
                if (vNum === undefined || vNum === null) {
                    if (rev.revision_number) vNum = rev.revision_number; // Alternative field
                }
                // Fallback to index if absolutely no version number (rare)
                if (vNum === undefined || vNum === null) {
                     vNum = i + 1;
                     console.warn(`[History] Revision at index ${i} has no version number. Assigned ${vNum}.`);
                }
                
                updateStatus(uiId, 'loading', `Archiving Rev ${vNum} (${i+1}/${revisions.length})`);
                console.log(`[History] 💾 Processing Revision ${vNum} (ID: ${rev.id})...`);

                // Retry Loop
                let success = false;
                let attempts = 0;
                const maxAttempts = 2; // Try up to 2 times

                while (!success && attempts < maxAttempts) {
                    attempts++;
                    try {
                        // A. Fetch Content
                        const [assetList, htmlContent] = await Promise.all([
                            getAssets(project.id, vNum),
                            getProjectHtml(project.id, vNum)
                        ]);

                        // B. Process Assets
                        const files = await processAssets(assetList, project.id, vNum);

                        // C. Add HTML
                        const hasIndex = Object.keys(files).some(k => k.toLowerCase() === 'index.html');

                        if (htmlContent) {
                            files['index.html'] = new TextEncoder().encode(htmlContent);
                        } else if (!hasIndex) {
                             console.warn(`[History] Rev ${vNum}: No HTML found in assets or API. Creating placeholder.`);
                             files['index.html'] = new TextEncoder().encode(`<!-- Version ${vNum}: Source Missing (API 403/404) -->`);
                        }

                        // D. Write to Zip Folder
                        const revFolder = revisionsFolder.folder(String(vNum));
                        for (const [path, content] of Object.entries(files)) {
                            revFolder.file(path.replace(/^\/+/, ''), content);
                        }

                        // E. Append to Commit Log
                        const date = rev.created_at || new Date().toISOString();
                        const author = rev.created_by?.username || username || 'unknown';
                        let msg = rev.title || rev.note || rev.description || `Version ${vNum}`;
                        msg = msg.replace(/\|/g, '-').replace(/[\r\n]+/g, ' '); 
                        
                        commitLog += `${vNum}|${date}|${author}|${msg}\n`;
                        success = true;

                        // Breathe
                        await new Promise(r => setTimeout(r, 100));

                    } catch (revError) {
                        console.error(`[History] ⚠️ Failed attempt ${attempts}/${maxAttempts} for Rev ${vNum}:`, revError);
                        if (attempts >= maxAttempts) {
                            // Give up on this revision but continue loop
                            commitLog += `${vNum}|${new Date().toISOString()}|system|FAILED_TO_ARCHIVE\n`;
                        } else {
                            // Backoff
                            await new Promise(r => setTimeout(r, 1000 * attempts));
                        }
                    }
                }
            }

            // 4. Write Metadata & Scripts
            outputFolder.file("commit_log.txt", commitLog);
            outputFolder.file("restore_git.sh", generateGitRestoreScript(), { unixPermissions: "755" });

        } 
        // --- PATH 2: Latest Only (Legacy) ---
        else {
            updateStatus(uiId, 'loading', 'Fetching latest revision...');
            console.log(`[Main] 🚀 Fetching LATEST version for ${project.id} (History skipped)`);
            
            // 1. Resolve Version
            let versionId = project.current_version;
            if (versionId === undefined || versionId === null) {
                versionId = project.latest_revision?.version || 
                            project.latest_version?.version || 
                            project.revision?.version;
            }

            // Fallback: Fetch metadata
            if (versionId === undefined || versionId === null) {
                 console.log(`[Main] No numeric version for ${project.id}, fetching metadata...`);
                 try {
                     const full = await getProjectById(project.id);
                     versionId = full?.current_version;
                     if (versionId === undefined || versionId === null) {
                         const revs = await getAllProjectRevisions(project.id);
                         versionId = revs[0]?.version;
                     }
                 } catch(e) { console.warn("Meta fetch fail:", e); }
            }

            if (versionId === undefined || versionId === null) throw new Error('No numeric version found');
            if (Number.isNaN(Number(versionId))) throw new Error(`Invalid version number: ${versionId}`);

            // 2. Download
            updateStatus(uiId, 'loading', 'Downloading assets...');
            const [assetList, htmlContent] = await Promise.all([
                getAssets(project.id, versionId),
                getProjectHtml(project.id, versionId)
            ]);

            const files = await processAssets(assetList, project.id, versionId);

            const htmlBuffer = htmlContent 
                ? new TextEncoder().encode(htmlContent)
                : new TextEncoder().encode(`<html><body><h1>${project.title}</h1><p>Source unavailable.</p></body></html>`);
            files['index.html'] = htmlBuffer;

            // 3. Write
            for (const [path, content] of Object.entries(files)) {
                outputFolder.file(path.replace(/^\/+/, ''), content);
            }
        }

        // --- Finalize Individual Zip ---
        if (mode === 'individual') {
            updateStatus(uiId, 'loading', 'Zipping...');
            const blob = await targetZip.generateAsync({ type: "blob" });
            const a = document.createElement('a');
            a.href = URL.createObjectURL(blob);
            a.download = `${username}_${projectFolderName}.zip`;
            a.click();
            URL.revokeObjectURL(a.href);
        }

        processedCount++;
        statProcessed.textContent = processedCount;
        updateStatus(uiId, 'done', mode === 'individual' ? 'Saved' : 'Packaged');
        
        // Save to Catalog
        addToCatalog(project);

    } catch (e) {
        console.error(`[Main] Error processing ${project.slug}:`, e);
        updateStatus(uiId, 'error', `Failed: ${e.message}`);
    }
}

function saveSettings() {
    const settings = {
        username: usernameInput.value,
        dateStart: dateStartInput.value,
        dateEnd: dateEndInput.value,
        downloadMode: downloadModeInput.value,
        delay: delayInput.value,
        skipForks: skipForksInput.checked,
        includeHistory: includeHistoryInput.checked,
        skipArchived: skipArchivedInput.checked
    };
    try { localStorage.setItem(SETTINGS_KEY, JSON.stringify(settings)); } catch(e){}
}

function loadSettings() {
    try {
        const raw = localStorage.getItem(SETTINGS_KEY);
        if (!raw) return;
        const s = JSON.parse(raw);
        if (s.username) usernameInput.value = s.username;
        if (s.dateStart) dateStartInput.value = s.dateStart;
        if (s.dateEnd) dateEndInput.value = s.dateEnd;
        if (s.downloadMode) downloadModeInput.value = s.downloadMode;
        if (s.delay) delayInput.value = s.delay;
        if (s.skipForks !== undefined) skipForksInput.checked = s.skipForks;
        if (s.includeHistory !== undefined) includeHistoryInput.checked = s.includeHistory;
        if (s.skipArchived !== undefined) skipArchivedInput.checked = s.skipArchived;
    } catch(e) {
        console.warn("Failed to load settings", e);
    }
}

async function startBackup() {
    saveSettings();
    const username = usernameInput.value.trim().replace('@', '');
    if (!username) return alert('Please enter a username');

    // Read Settings
    const mode = downloadModeInput.value;
    const delay = parseInt(delayInput.value) || 3000;
    const skipForks = skipForksInput.checked;
    const includeHistory = includeHistoryInput.checked;
    const skipArchived = skipArchivedInput.checked;
    
    const startDate = dateStartInput.value ? new Date(dateStartInput.value) : null;
    const endDate = dateEndInput.value ? new Date(dateEndInput.value) : null;

    console.log(`[Main] Backup config: User=${username}, Mode=${mode}, Delay=${delay}, SkipForks=${skipForks}`);

    // Reset UI
    isRunning = true;
    stopRequested = false;
    foundProjects = [];
    processedCount = 0;
    zip = new JSZip(); // Always init for potential Batch usage
    
    projectListEl.innerHTML = '';
    statTotal.textContent = '0';
    statProcessed.textContent = '0';
    statSize.textContent = '0 Bytes';
    
    startBtn.disabled = true;
    stopBtn.disabled = false;
    stopBtn.textContent = (mode === 'batch') ? "Stop & Save" : "Stop";
    usernameInput.disabled = true;

    try {
        const userFolder = zip.folder(username);
        const generator = getAllUserProjectsGenerator(username);
        
        for await (const project of generator) {
            if (stopRequested) break;

            // --- FILTERING LOGIC ---
            
            // 1. Date Filter
            if (startDate || endDate) {
                const pDate = new Date(project.created_at); // or updated_at? Usually creation for archive.
                if (startDate && pDate < startDate) continue;
                if (endDate && pDate > endDate) continue;
            }

            // 2. Fork Filter
            if (skipForks && project.parent_id) {
                console.log(`[Main] Skipping fork: ${project.slug} (Parent: ${project.parent_id})`);
                continue;
            }

            console.log(`[Main] Discovered project: ${project.id}`);
            foundProjects.push(project);
            statTotal.textContent = foundProjects.length;
            
            const el = createProjectElement(project);
            projectListEl.appendChild(el);

            if (!project.id) {
                updateStatus('unknown', 'error', 'Missing ID');
                continue;
            }

            // 3. Archive/Catalog Filter
            if (skipArchived && isArchived(project.id)) {
                updateStatus(project.id, 'done', 'Already Archived (Skipped)');
                // We do NOT increment 'processedCount' for the batch zip logic, 
                // because it's not in THIS zip file.
                // But we can visually indicate it's done.
                continue;
            }

            // Process
            await processProject(project, username, {
                mode: mode,
                rootZipFolder: userFolder,
                includeHistory: includeHistory
            });
            
            // Rate Limit
            if (delay > 0) {
                console.log(`[Main] Waiting ${delay}ms...`);
                await new Promise(r => setTimeout(r, delay));
            }
        }

    } catch (e) {
        console.error("[Main] Loop error:", e);
        alert(`Error: ${e.message}`);
    } finally {
        finishBackup(mode);
    }
}

async function finishBackup(mode) {
    isRunning = false;
    startBtn.disabled = false;
    stopBtn.disabled = true;
    stopBtn.textContent = "Stop";
    usernameInput.disabled = false;

    // In individual mode, we are done.
    if (mode === 'individual') {
        alert(`Done! Processed ${processedCount} projects.`);
        return;
    }

    // In batch mode, we check if we have anything to zip
    if (processedCount === 0) {
        alert("No projects were processed.");
        return;
    }

    // Generate Giant Zip
    startBtn.textContent = "Saving ZIP...";
    startBtn.disabled = true;

    try {
        const content = await zip.generateAsync({ type: "blob" }, (metadata) => {
             statSize.textContent = `Zipping: ${metadata.percent.toFixed(1)}%`;
        });
        
        statSize.textContent = formatBytes(content.size);
        
        const a = document.createElement('a');
        a.href = URL.createObjectURL(content);
        a.download = `${usernameInput.value.replace('@','')}_full_backup_${Date.now()}.zip`;
        a.click();
        URL.revokeObjectURL(a.href);

    } catch (e) {
        alert("Error generating ZIP: " + e.message);
    }

    startBtn.textContent = "Start Backup";
    startBtn.disabled = false;
}

startBtn.addEventListener('click', startBackup);
stopBtn.addEventListener('click', () => {
    if (isRunning) {
        stopRequested = true;
        stopBtn.textContent = "Stopping...";
        stopBtn.disabled = true;
    }
});

loadSettings();